import { FiDownload, FiTrendingUp, FiUsers, FiBook, FiActivity } from 'react-icons/fi'

function AdminReports() {
  const reportTypes = [
    { id: 1, name: 'Student Performance Report', description: 'Detailed analysis of student grades and progress', icon: FiTrendingUp, color: 'orange' },
    { id: 2, name: 'Enrollment Report', description: 'Course enrollment statistics and trends', icon: FiUsers, color: 'blue' },
    { id: 3, name: 'Course Analytics', description: 'Course completion rates and feedback', icon: FiBook, color: 'green' },
    { id: 4, name: 'System Activity Report', description: 'Platform usage and activity metrics', icon: FiActivity, color: 'purple' }
  ]

  const recentReports = [
    { id: 1, name: 'Fall 2024 Enrollment Report', generatedAt: '2024-05-10', generatedBy: 'Admin Pham D', size: '2.4 MB' },
    { id: 2, name: 'Student Performance Q1 2024', generatedAt: '2024-04-15', generatedBy: 'Admin Nguyen A', size: '3.1 MB' },
    { id: 3, name: 'Course Completion Analysis', generatedAt: '2024-04-01', generatedBy: 'Admin Tran B', size: '1.8 MB' }
  ]

  return (
    <>
      <div className="dashboard-header">
        <div className="dashboard-welcome">
          <h1>Reports</h1>
          <p>Generate and download system reports.</p>
        </div>
        <button className="btn btn-primary">
          <FiDownload style={{ marginRight: '8px' }} />
          Generate Custom Report
        </button>
      </div>

      <div className="section">
        <div className="section-header">
          <h2>Report Types</h2>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '16px' }}>
          {reportTypes.map(report => {
            const Icon = report.icon
            return (
              <div key={report.id} className="card" style={{ padding: '24px', cursor: 'pointer' }}>
                <div style={{ display: 'flex', gap: '16px', marginBottom: '16px' }}>
                  <div className={`stat-icon ${report.color}`} style={{ width: '56px', height: '56px', fontSize: '24px' }}>
                    <Icon />
                  </div>
                  <div style={{ flex: 1 }}>
                    <h3 style={{ fontSize: '16px', fontWeight: '600', marginBottom: '4px' }}>{report.name}</h3>
                    <p style={{ fontSize: '13px', color: 'var(--gray-600)' }}>{report.description}</p>
                  </div>
                </div>
                <button className="btn btn-primary" style={{ width: '100%' }}>
                  <FiDownload style={{ marginRight: '8px' }} />
                  Generate Report
                </button>
              </div>
            )
          })}
        </div>
      </div>

      <div className="section" style={{ marginTop: '24px' }}>
        <div className="section-header">
          <h2>Recent Reports</h2>
          <a href="#">View All</a>
        </div>

        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ borderBottom: '2px solid var(--gray-200)' }}>
                <th style={{ padding: '12px', textAlign: 'left', fontSize: '13px', fontWeight: '600', color: 'var(--gray-700)' }}>Report Name</th>
                <th style={{ padding: '12px', textAlign: 'center', fontSize: '13px', fontWeight: '600', color: 'var(--gray-700)' }}>Generated Date</th>
                <th style={{ padding: '12px', textAlign: 'left', fontSize: '13px', fontWeight: '600', color: 'var(--gray-700)' }}>Generated By</th>
                <th style={{ padding: '12px', textAlign: 'center', fontSize: '13px', fontWeight: '600', color: 'var(--gray-700)' }}>File Size</th>
                <th style={{ padding: '12px', textAlign: 'center', fontSize: '13px', fontWeight: '600', color: 'var(--gray-700)' }}>Action</th>
              </tr>
            </thead>
            <tbody>
              {recentReports.map(report => (
                <tr key={report.id} style={{ borderBottom: '1px solid var(--gray-100)' }}>
                  <td style={{ padding: '16px', fontSize: '14px', fontWeight: '500', color: 'var(--gray-900)' }}>{report.name}</td>
                  <td style={{ padding: '16px', textAlign: 'center', fontSize: '13px', color: 'var(--gray-600)' }}>
                    {new Date(report.generatedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                  </td>
                  <td style={{ padding: '16px', fontSize: '13px', color: 'var(--gray-600)' }}>{report.generatedBy}</td>
                  <td style={{ padding: '16px', textAlign: 'center', fontSize: '13px', color: 'var(--gray-600)' }}>{report.size}</td>
                  <td style={{ padding: '16px', textAlign: 'center' }}>
                    <button className="btn btn-primary" style={{ fontSize: '13px', padding: '6px 16px' }}>
                      <FiDownload size={14} style={{ marginRight: '6px' }} />
                      Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <div className="section" style={{ marginTop: '24px' }}>
        <div className="section-header">
          <h2>Quick Stats</h2>
        </div>

        <div className="stats-grid">
          <div className="stat-card">
            <div className="stat-header">
              <div>
                <div className="stat-value">2,847</div>
                <div className="stat-label">Total Users</div>
              </div>
              <div className="stat-icon orange">
                <FiUsers />
              </div>
            </div>
            <div className="stat-change positive">+137 this month</div>
          </div>
          <div className="stat-card">
            <div className="stat-header">
              <div>
                <div className="stat-value">156</div>
                <div className="stat-label">Active Courses</div>
              </div>
              <div className="stat-icon blue">
                <FiBook />
              </div>
            </div>
            <div className="stat-change positive">+12 this semester</div>
          </div>
          <div className="stat-card">
            <div className="stat-header">
              <div>
                <div className="stat-value">89%</div>
                <div className="stat-label">Completion Rate</div>
              </div>
              <div className="stat-icon green">
                <FiTrendingUp />
              </div>
            </div>
            <div className="stat-change positive">+4% from last term</div>
          </div>
          <div className="stat-card">
            <div className="stat-header">
              <div>
                <div className="stat-value">99.9%</div>
                <div className="stat-label">System Uptime</div>
              </div>
              <div className="stat-icon purple">
                <FiActivity />
              </div>
            </div>
            <div className="stat-change positive">Last 30 days</div>
          </div>
        </div>
      </div>
    </>
  )
}

export default AdminReports
